// ClassReady - Data-driven lesson framework
// Lesson data loaded from JSON at startup

var cur=0,userName="",ci=0,cf=false;
var qi=0,qa=-1,qscore=0;
var pyTiles=[],pySel=-1,pyDone=0,pyTotal=0;
var D=null,sentences=[],qz=[];
function pyInit(){pySel=-1;pyDone=0;}

var modNames=["R0 Warm-up","R2 Words","R2 Sentences","R1 Cards","R4 Pinyin","R5 Write","Quiz"];
var modIds=["R0","R2W","R2S","R1","R4","R5","Quiz"];

function loadLesson(data){D=data;
sentences=[];var seen={};
if(D.readingData){D.readingData.forEach(function(sc){sc.dialogue.forEach(function(ln){var t=ln.chinese.trim();if(t&&!seen[t]){seen[t]=true;sentences.push({c:t,p:ln.pinyin,e:ln.english});}});});}
qz=D.quiz||[];
document.getElementById("startBtn").disabled=false;
document.getElementById("startBtn").textContent="▶ Start Pre-class";}

var lessonId=new URLSearchParams(window.location.search).get("lesson")||"HSK1-L2";
fetch("data/lessons/"+lessonId+".json").then(function(r){if(!r.ok)throw Error();return r.json();}).then(function(d){loadLesson(d);}).catch(function(){console.error("Failed to load lesson");});

function start(){userName=document.getElementById("ni").value.trim()||"Student";document.getElementById("welcome").style.display="none";document.getElementById("lesson").style.display="block";showMod(0);}
function showMod(i){cur=i;document.getElementById("modLabel").textContent=modIds[i]+" · "+modNames[i];document.getElementById("prevBtn").style.display=i>0?"block":"none";document.getElementById("nextBtn").textContent=i<6?"Next ▶":"Done";closeChar();var el=document.getElementById("modContent");var fns=[renderR0,renderR2,renderR2b,renderR1,renderR4,renderR5,renderQuiz];el.innerHTML=fns[i]();if(i===4)setTimeout(function(){pyInit();},50);if(i===1)setTimeout(function(){initAudio();},50);if(i===2)setTimeout(function(){initSentences();},50);if(i===3)setTimeout(function(){initSwipe();},50);}
function nav(d){var n=cur+d;if(n>=0&&n<7)showMod(n);}

function renderR0(){var h='<div class="ca"><div class="t">Topic Warm-up <span class="c">R0</span></div><p style="color:#8b7355;font-size:13px">Get ready for the topic</p><b>Useful phrases</b>';h+='<div style="display:flex;gap:12px;padding:10px;background:#fcf8f6;border-radius:10px;margin:8px 0;border:1px solid #f0e8e4"><div style="font-size:20px;font-weight:700;color:#8b1a1a">对不起</div><div style="font-size:13px;color:#8b7355"><i>duìbuqǐ</i> - sorry<br><span style="color:#a08070">Apologizing when you make a mistake.</span></div></div>';h+='<div style="display:flex;gap:12px;padding:10px;background:#fcf8f6;border-radius:10px;margin:8px 0;border:1px solid #f0e8e4"><div style="font-size:20px;font-weight:700;color:#8b1a1a">没关系</div><div style="font-size:13px;color:#8b7355"><i>méi guānxi</i> - that is all right<br><span style="color:#a08070">Responding when someone apologizes.</span></div></div>';h+='<div style="margin-top:12px"><b>Questions / 想一想</b></div>';h+='<div style="padding:10px;background:#fcf8f6;border-radius:10px;margin:8px 0;border:1px solid #f0e8e4"><b>Q1</b> What is your name?<br><span style="color:#8b7355;font-size:13px"><i>Nǐ jiào shénme míngzì?</i></span></div>';h+='<div style="padding:10px;background:#fcf8f6;border-radius:10px;margin:8px 0;border:1px solid #f0e8e4"><b>Q2</b> How to say sorry?<br><span style="color:#8b7355;font-size:13px"><i>Yòng Zhōngwén zěnme shuō duìbuqǐ?</i></span></div>';return h+'</div>';}
function renderR2(){var h='<div class="ca"><div class="t">Read Words <span class="c">R2W</span></div><p style="color:#8b7355;font-size:13px">Tap 🔊 to hear each word</p>';for(var i=0;i<D.vocabData.length;i++){var v=D.vocabData[i];h+='<div class="ri"><div class="hz">'+v.word+'</div><div class="py"><i>'+v.pinyin+'</i></div><div class="en">'+v.english+'</div><button class="sb" onclick="speakWord('+i+')">🔊</button></div>';}h+='<button class="btn" onclick="speakAll()">🔊 Play All</button></div>';return h;}
function speakWord(i){if(!window.speechSynthesis)return;var v=D.vocabData[i];window.speechSynthesis.cancel();var u1=new SpeechSynthesisUtterance(v.word);u1.lang="zh-CN";u1.rate=0.8;window.speechSynthesis.speak(u1);var u2=new SpeechSynthesisUtterance(v.pinyin);u2.lang="zh-CN";u2.rate=0.8;window.speechSynthesis.speak(u2);}
function speakAll(){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();D.vocabData.forEach(function(v,i){setTimeout(function(){var u1=new SpeechSynthesisUtterance(v.word);u1.lang="zh-CN";u1.rate=0.8;window.speechSynthesis.speak(u1);var u2=new SpeechSynthesisUtterance(v.pinyin);u2.lang="zh-CN";u2.rate=0.8;window.speechSynthesis.speak(u2);},i*2500);});}
function initAudio(){}

function renderR2b(){var h='<div class="ca"><div class="t">Read Sentences <span class="c">R2S</span></div><p style="color:#8b7355;font-size:13px">Tap 🔊 to hear each sentence</p>';for(var i=0;i<sentences.length;i++){var s=sentences[i];h+='<div class="ri" style="flex-direction:column;padding:8px 14px"><div style="font-size:12px;color:#8b7355;text-align:center"><i>'+s.p+'</i></div><div style="display:flex;align-items:center;gap:8px"><div class="hz" style="font-size:18px;white-space:nowrap;flex:1">'+s.c+'</div><button style="padding:2px 8px;border:none;border-radius:6px;background:#c0392b;color:#fff;font-size:16px;cursor:pointer" onclick="spkS('+i+')">🔊</button></div><div style="font-size:11px;color:#a08070;margin-top:2px">'+s.e+'</div></div>';}h+='<button class="btn" onclick="spkAllS()">🔊 Play All Sentences</button></div>';return h;}
function spkS(i){if(!window.speechSynthesis)return;var s=sentences[i];window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(s.c);u.lang="zh-CN";u.rate=0.8;window.speechSynthesis.speak(u);}
function spkAllS(){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();sentences.forEach(function(s,i){setTimeout(function(){var u=new SpeechSynthesisUtterance(s.c);u.lang="zh-CN";u.rate=0.8;window.speechSynthesis.speak(u);},i*3000);});}
function initSentences(){}

function renderR1(){return renderCard();}
function renderCard(){var v=D.vocabData[ci];if(!v)return"";var fs=cf?"transform:rotateY(180deg)":"";var bs=cf?"":"transform:rotateY(180deg)";var h='<div class="ca"><div class="t">Vocab Cards <span class="c">R1</span></div><p style="color:#8b7355;font-size:13px">Swipe right = know / left = reveal</p><div id="cardCont" style="perspective:1000px;cursor:grab;margin:12px 0;user-select:none;touch-action:none"><div id="cardInner" style="transition:transform .5s;transform-style:preserve-3d;position:relative;height:260px">';h+='<div style="'+fs+';position:absolute;width:100%;height:100%;backface-visibility:hidden;border-radius:20px;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:28px;background:#fff;border:2px solid #f0e8e4;box-shadow:0 4px 16px rgba(0,0,0,.06)"><div style="font-size:56px;font-weight:700;color:#3d2b1f;margin-bottom:8px">'+v.word+'</div><div style="font-size:18px;color:#8b7355">'+v.pinyin+'</div></div>';h+='<div style="'+bs+';position:absolute;width:100%;height:100%;backface-visibility:hidden;border-radius:20px;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:28px;background:#fcecea;border:2px solid #f0e0da;box-shadow:0 4px 16px rgba(0,0,0,.06)"><div style="font-size:24px;font-weight:700;color:#8b1a1a;text-align:center">'+v.english+'</div></div></div></div>';h+='<div style="text-align:center;font-size:13px;color:#8b7355">'+(ci+1)+'/'+D.vocabData.length+'</div><div style="display:flex;gap:12px;margin-top:8px"><button class="nb b" onclick="ci=Math.max(0,ci-1);cf=false;showMod(cur)" style="flex:1">◀ Prev</button><button class="nb f" onclick="ci=Math.min(8,ci+1);cf=false;showMod(cur)" style="flex:1">Next ▶</button></div></div>';return h;}
function initSwipe(){var el=document.getElementById("cardCont");if(!el)return;var sx=0,cx=0,dr=false;var st=function(e){sx=e.type.indexOf("mouse")===0?e.clientX:e.touches[0].clientX;dr=true;el.style.transition="none";};var mv=function(e){if(!dr)return;e.preventDefault();cx=e.type.indexOf("mouse")===0?e.clientX:e.touches[0].clientX;var d=cx-sx;el.style.transform="translateX("+d+"px)rotate("+(d*0.05)+"deg)";};var en=function(){if(!dr)return;dr=false;var d=cx-sx;el.style.transition="transform 0.3s";if(d>80){el.style.transform="translateX(400px)";setTimeout(function(){ci=Math.min(8,ci+1);cf=false;showMod(cur);},300);}else if(d<-80){el.style.transform="translateX(-400px)";setTimeout(function(){cf=!cf;showMod(cur);},300);}else{el.style.transform="translateX(0)";}};el.addEventListener("touchstart",st,{passive:true});el.addEventListener("touchmove",mv,{passive:false});el.addEventListener("touchend",en);el.addEventListener("mousedown",st);el.addEventListener("mousemove",mv);el.addEventListener("mouseup",en);el.addEventListener("mouseleave",en);}

function renderR4(){pyTiles=[];pySel=-1;pyDone=0;var pairs=[];for(var i=0;i<D.vocabData.length;i++){var v=D.vocabData[i];pairs.push({h:v.word,p:v.pinyin,pid:i});}pyTotal=pairs.length;for(var i=0;i<pairs.length;i++){pyTiles.push({t:pairs[i].h,ty:"h",pi:pairs[i].pid,ok:0});pyTiles.push({t:pairs[i].p,ty:"p",pi:pairs[i].pid,ok:0});}for(var i=pyTiles.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var tmp=pyTiles[i];pyTiles[i]=pyTiles[j];pyTiles[j]=tmp;}var h='<div class="ca"><div class="t">Pinyin Match <span class="c">R4</span></div><p style="color:#8b7355;font-size:13px">Click hanzi then pinyin</p><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin-top:12px">';for(var i=0;i<pyTiles.length;i++){var c=pyTiles[i];h+='<div class="gc" onclick="pyClick('+i+')">'+c.t+'</div>';}h+='</div><div style="text-align:center;font-size:13px;margin-top:8px" id="pySc">0/'+pyTotal+'</div></div>';return h;}
function pyClick(i){var c=pyTiles[i];if(c.ok)return;var els=document.getElementsByClassName("gc");if(pySel===-1){pySel=i;els[i].className="gc s";return;}if(pyTiles[pySel].pi===c.pi&&pyTiles[pySel].ty!==c.ty){c.ok=1;pyTiles[pySel].ok=1;pyDone++;els[i].className="gc o";els[pySel].className="gc o";pySel=-1;document.getElementById("pySc").textContent=pyDone+"/"+pyTotal;if(pyDone===pyTotal)alert("All matched!");}else{els[i].className="gc w";els[pySel].className="gc w";setTimeout(function(){els[i].className="gc";els[pySel].className="gc";pySel=-1;},400);}}

function renderR5(){var seen={},chars=[];for(var v=0;v<D.vocabData.length;v++){var w=D.vocabData[v].word;for(var c=0;c<w.length;c++){var ch=w[c];if(!seen[ch]){seen[ch]=true;chars.push({h:ch,s:5});}}}window.r5chars=chars;var h='<div class="ca"><div class="t">Character Writing <span class="c">R5</span></div><p style="color:#8b7355;font-size:13px">Click a character</p><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px">';for(var i=0;i<chars.length;i++){h+='<div style="text-align:center;padding:10px;border-radius:10px;border:1px solid #f0e8e4;background:#fff;cursor:pointer" onclick="showChar('+i+')"><div style="font-size:28px;font-weight:700;color:#3d2b1f">'+chars[i].h+'</div><div style="font-size:11px;color:#a08070;margin-top:4px">'+chars[i].s+' strokes</div></div>';}h+='</div></div>';return h;}
function showChar(i){var ch=window.r5chars[i];if(!ch)return;document.getElementById("charBig").textContent=ch.h;document.getElementById("charInfo2").innerHTML="Stroke count: <b>"+ch.s+"</b>";document.getElementById("charDetail").style.display="block";initCanvas(ch.h);fetch("data/"+encodeURIComponent(ch.h)+".json").then(function(r){if(!r.ok)throw Error();return r.json();}).then(function(d){try{if(typeof HanziWriter!=="undefined"){if(window.hw)try{window.hw.destroy();}catch(e){}window.hw=HanziWriter.create("writeCanvas",ch.h,{width:240,height:240,padding:5,strokeAnimationSpeed:3,delayBetweenStrokes:200,data:d});window.hw.animateCharacter();}}catch(e){}}).catch(function(){})}
function closeChar(){document.getElementById("charDetail").style.display="none";if(window.hw)try{window.hw.destroy();}catch(e){}}
function initCanvas(ch){var c=document.getElementById("writeCanvas");if(!c)return;var ctx=c.getContext("2d");c.width=240;c.height=240;ctx.clearRect(0,0,240,240);ctx.fillStyle="#f0e8e4";ctx.fillRect(0,0,240,240);ctx.fillStyle="rgba(0,0,0,0.08)";ctx.font="120px \"Microsoft YaHei\",sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(ch,120,120);window.drawing=false;var sd=function(e){window.drawing=true;var p=getPos(e,c);ctx.beginPath();ctx.moveTo(p.x,p.y);};var md=function(e){if(!window.drawing)return;e.preventDefault();var p=getPos(e,c);ctx.lineTo(p.x,p.y);ctx.strokeStyle="#c0392b";ctx.lineWidth=4;ctx.lineCap="round";ctx.stroke();};var ed=function(){window.drawing=false;};c.onmousedown=sd;c.onmousemove=md;c.onmouseup=ed;c.onmouseleave=ed;c.ontouchstart=function(e){e.preventDefault();var t=e.touches[0];sd({clientX:t.clientX,clientY:t.clientY});};c.ontouchmove=function(e){e.preventDefault();var t=e.touches[0];md({preventDefault:function(){},clientX:t.clientX,clientY:t.clientY});};c.ontouchend=ed;}
function getPos(e,canvas){var r=canvas.getBoundingClientRect();return{x:(e.clientX-r.x)*canvas.width/r.width,y:(e.clientY-r.y)*canvas.height/r.height};}
function clearCanvas(){var c=document.getElementById("writeCanvas");if(!c)return;var ctx=c.getContext("2d");ctx.clearRect(0,0,240,240);ctx.fillStyle="#f0e8e4";ctx.fillRect(0,0,240,240);var ch=document.getElementById("charBig").textContent;if(ch){ctx.fillStyle="rgba(0,0,0,0.08)";ctx.font="120px \"Microsoft YaHei\",sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(ch,120,120);}}

var qResults=[];
function renderQuiz(){qi=0;qa=-1;qscore=0;qResults=[];return renderQ();}
function renderQ(){if(qi>=qz.length)return renderResult();var q=qz[qi];var h='<div class="ca"><div class="t">Quiz <span class="c">Quiz</span></div><p style="color:#8b7355;font-size:13px">'+(qi+1)+'/'+qz.length+'</p><div style="font-size:16px;font-weight:600;margin:12px 0">'+(qi+1)+'. '+q.q+'</div>';for(var i=0;i<q.o.length;i++){h+='<button class="qo" onclick="ans('+i+')">'+q.o[i]+'</button>';}h+='<div style="text-align:center;font-size:13px;margin-top:8px">'+qscore+'/'+qi+'</div></div>';return h;}
function ans(i){if(qa!==-1)return;qa=i;for(var j=0;j<qz[qi].o.length;j++){var el=document.getElementsByClassName("qo")[j];if(j===qz[qi].a)el.className="qo r";else if(j===i)el.className="qo w";}var correct=(i===qz[qi].a);if(correct)qscore++;qResults.push({qNum:qi,qText:qz[qi].q,correct:correct});setTimeout(function(){qi++;qa=-1;if(qi>=qz.length){document.getElementById("modContent").innerHTML=renderResult();}else{document.getElementById("modContent").innerHTML=renderQ();}},800);}
var lessonId=new URLSearchParams(window.location.search).get("lesson")||"HSK1-L2";function saveResult(){if(!userName||!qResults.length)return;var btn=document.getElementById("saveBtn");if(btn)btn.disabled=true;fetch("/api/save-result",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:userName,lesson:lessonId,score:qscore,total:qz.length,details:qResults})}).then(function(r){return r.json();}).then(function(d){if(d.ok){document.getElementById("saveStatus").textContent="✓ Saved! 已保存";document.getElementById("saveStatus").style.color="#28a745";}}).catch(function(){document.getElementById("saveStatus").textContent="Save failed";document.getElementById("saveStatus").style.color="#dc3545";});}
function renderResult(){var pct=Math.round(qscore/qz.length*100);var grade=pct===100?"🎉 Perfect!":pct>=70?"👍 Good job!":pct>=50?"💪 Keep trying":"📚 Need more practice";var h='<div class="ca" style="text-align:center;padding:20px"><div style="font-size:48px;margin-bottom:8px">🎉</div><div style="font-size:22px;font-weight:700;margin-bottom:4px">'+qscore+'/'+qz.length+' ('+pct+'%)</div><div style="font-size:14px;color:#8b7355;margin-bottom:12px">'+grade+'</div>';h+='<div style="font-size:13px;color:#a08070;margin-bottom:12px;padding:8px;background:#fcf8f6;border-radius:8px">Pre-class complete!<br>You reviewed '+qz.length+' questions.</div>';h+='<div style="text-align:left;margin-bottom:12px"><b style="font-size:13px">Details:</b>';for(var i=0;i<qResults.length;i++){var r=qResults[i];h+='<div style="font-size:12px;padding:6px 0;border-bottom:1px solid #f0e8e4;display:flex;align-items:center;gap:6px"><span style="color:'+(r.correct?"#28a745":"#dc3545")+'">'+(r.correct?"✓":"✗")+'</span><span>'+r.qText+'</span></div>';}h+='</div><div style="text-align:left;margin-top:8px"><div class="gx"><span class="la">1</span>'+D.grammarPoints[0]+'</div><div class="gx"><span class="la">2</span>'+D.grammarPoints[1]+'</div></div>';h+='<div style="margin-top:12px"><button class="btn" id="saveBtn" onclick="saveResult()" style="margin-top:0">💾 Save Result / 保存结果</button>';h+='<div id="saveStatus" style="text-align:center;font-size:12px;color:#a08070;margin-top:6px">Your result will be saved to the server</div>';h+='<button class="btn" onclick="start()" style="margin-top:8px">🔄 Restart</button></div>';return h;}
