(function () {
  var group1=['好','茶','狗','猫','菜','吃','喝','七','写','请','五','书','坐','人','睡'];
  var toneAnswer={'好':'hǎo','茶':'chá','狗':'gǒu','猫':'māo','菜':'cài','吃':'chī','喝':'hē','七':'qī','写':'xiě','请':'qǐng','五':'wǔ','书':'shū','坐':'zuò','人':'rén','睡':'shuì'};
  var toneOptions={'好':['hāo','háo','hǎo','hào'],'茶':['chā','chá','chǎ','chà'],'狗':['gōu','góu','gǒu','gòu'],'猫':['māo','máo','mǎo','mào'],'菜':['cāi','cái','cǎi','cài'],'吃':['chī','chí','chǐ','chì'],'喝':['hē','hé','hě','hè'],'七':['qī','qí','qǐ','qì'],'写':['xiē','xié','xiě','xiè'],'请':['qīng','qíng','qǐng','qìng'],'五':['wū','wú','wǔ','wù'],'书':['shū','shú','shǔ','shù'],'坐':['zuō','zuó','zuǒ','zuò'],'人':['rēn','rén','rěn','rèn'],'睡':['shuī','shuí','shuǐ','shuì']};
  var group2=[['中国','Zhōngguó'],['手机','shǒujī'],['桌子','zhuōzi'],['打车','dǎchē'],['朋友','péngyou'],['休息','xiūxi'],['牛奶','niúnǎi'],['高兴','gāoxìng'],['面包','miànbāo'],['房间','fángjiān'],['电脑','diànnǎo'],['饭店','fàndiàn'],['鸡蛋','jīdàn'],['老师','lǎoshī'],['学生','xuéshēng'],['杯子','bēizi'],['空调','kōngtiáo'],['出租车','chūzūchē']];
  var group3=[['你好！','Nǐ hǎo!'],['大家好！','Dàjiā hǎo!'],['老师，您好！','Lǎoshī, nín hǎo!'],['谢谢！','Xièxie!'],['不客气！','Bú kèqi!'],['你们好！','Nǐmen hǎo!'],['同学们，再见！','Tóngxuémen, zàijiàn!'],['老师，再见！','Lǎoshī, zàijiàn!'],['我是学生。','Wǒ shì xuéshēng.'],['我很好。','Wǒ hěn hǎo.']];
  var initials=[['双唇音','b / p / m','双唇闭合或接近。b、p 阻塞气流，m 让气流从鼻腔通过。','Close or bring the lips together. b and p stop the air; m is nasal.','Сомкните или приблизьте губы. b и p задерживают воздух, m — носовой звук.'],['唇齿音','f','上齿接近下唇，气流从缝隙摩擦通过。','Upper teeth touch the lower lip; air passes through the gap.','Верхние зубы касаются нижней губы; воздух проходит через щель.'],['舌尖中音','d / t / n / l','舌尖接触或接近上齿龈。','Raise the tongue tip to the ridge behind the upper teeth.','Поднимите кончик языка к альвеолам за верхними зубами.'],['舌根音','g / k / h','舌根抬向软腭。','Raise the back of the tongue toward the soft palate.','Поднимите заднюю часть языка к мягкому нёбу.'],['舌面音','j / q / x','舌面前部接近硬腭，嘴角向两边展开。','Bring the front of the tongue near the hard palate and spread the lips.','Приблизьте переднюю часть языка к твёрдому нёбу и растяните губы.'],['翘舌音','zh / ch / sh / r','舌尖向上翘，靠近硬腭前部。','Curl the tongue tip toward the front of the hard palate.','Загните кончик языка к передней части твёрдого нёба.'],['平舌音','z / c / s','舌尖靠近上齿背，不翘舌。','Keep the tongue tip flat near the upper teeth; do not curl it.','Держите кончик языка ровно у верхних зубов, не загибайте его.']];
  var finals=[['单韵母','a / o / e / i / u / ü'],['复韵母','ai / ei / ao / ou'],['i 类韵母','ia / iao / ie / iu / ian / in / iang / ing / iong'],['u 类韵母','ua / uo / uai / ui / uan / un / uang / ueng'],['ü 类韵母','üe / üan / ün'],['鼻韵母','an / en / ang / eng / ong'],['特殊韵母','er']];
  var tones=[['第一声','mā','妈','高而平'],['第二声','má','麻','由低向高'],['第三声','mǎ','马','先降后升'],['第四声','mà','骂','由高向低'],['轻声','ma','吗','短而轻']];
  function rotate(a,i){i=i%a.length;return a.slice(i).concat(a.slice(0,i));}
  function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function render(){var ap=this,step=this.pyzStep||0,sub=this.pyzSub||0,qi=this.pyzQ||0,picked=this.pyzAnswer;var tabs=['拼音介绍 / Introduction','声母 / Initials','韵母 / Finals','声调 / Tones','拼合练习 / Blend','练习 / Practice'];var h='<div class="panel" style="text-align:left;max-width:1080px;width:100%"><h3 style="color:var(--blue);margin:0 0 14px;text-align:center">拼音学习与拼合练习 <span style="font-size:14px;color:#888">Pinyin Lab</span></h3><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-bottom:16px">';tabs.forEach(function(t,i){h+='<button class="grammar-tab'+(step===i?' active':'')+'" onclick="ap.pyzStep='+i+';ap.pyzSub=0;ap.pyzQ=0;ap.pyzAnswer=-1;ap._r()">'+t+'</button>'});h+='</div>';
    if(step===0){h+='<div style="background:#fff;border:1px solid var(--line);border-radius:18px;padding:26px;line-height:1.8"><h2 style="margin-top:0">什么是拼音？ / What is Pinyin?</h2><p>汉语拼音用拉丁字母表示普通话的读音。一个音节通常由声母、韵母和声调组成。</p><p> Pinyin uses Latin letters to show Mandarin pronunciation. A syllable usually has an initial, a final and a tone.</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:18px;text-align:center"><div class="formula-box"><b>声母</b><br><small>initial<br>开头的辅音</small></div><div class="formula-box"><b>韵母</b><br><small>final<br>音节的主要部分</small></div><div class="formula-box"><b>声调</b><br><small>tone<br>声音的高低变化</small></div></div><div style="margin-top:18px;background:#edf3ff;border-radius:14px;padding:14px;text-align:center;font-size:24px;font-weight:900">h + ǎo = hǎo → 好</div></div>'}
    if(step===1){h+='<div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:center;margin-bottom:16px">';initials.forEach(function(g,i){h+='<button class="grammar-tab'+(sub===i?' active':'')+'" onclick="ap.pyzSub='+i+';ap._r()"><b>'+g[0]+'</b><br><small>'+g[1]+'</small></button>'});h+='</div>';var g=initials[sub]||initials[0];h+='<div style="background:#fff;border:1px solid var(--line);border-radius:18px;padding:26px;max-width:820px;margin:auto;text-align:center"><div style="font-size:40px;font-weight:900;color:var(--blue);margin-bottom:16px">'+g[1]+'</div><div style="text-align:left;background:#f8faf3;border-radius:14px;padding:18px;line-height:1.8"><b>发音方法 / Method</b><br>'+g[2]+'<br><span style="color:#55719b">English: '+g[3]+'</span><br><span style="color:#8b5b72">Русский: '+g[4]+'</span></div><div style="margin-top:16px"><img src="images/pinyin_tongue_positions.svg" alt="Tongue positions" style="width:100%;border-radius:16px;border:1px solid var(--line)"></div></div>'}
    if(step===2){h+='<div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:center;margin-bottom:16px">';finals.forEach(function(g,i){h+='<button class="grammar-tab'+(sub===i?' active':'')+'" onclick="ap.pyzSub='+i+';ap._r()"><b>'+g[0]+'</b><br><small>'+g[1]+'</small></button>'});h+='</div>';var f=finals[sub]||finals[0];h+='<div style="background:#fff;border:1px solid var(--line);border-radius:18px;padding:28px;text-align:center"><div style="font-size:34px;font-weight:900;color:var(--blue)">'+f[1]+'</div><p style="line-height:1.8">韵母是音节中声音最响亮、最主要的部分。<br><span style="color:#55719b">A final is the main, most prominent part of a syllable.</span></p><div style="background:#edf3ff;border-radius:14px;padding:14px;font-size:13px">本组包含 '+f[1].split(' / ').length+' 个韵母；全部共 36 个。<br>This group contains '+f[1].split(' / ').length+' finals; 36 finals in total.</div></div>'}
    if(step===3){h+='<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px">';tones.forEach(function(t){h+='<div class="formula-box" style="text-align:center"><b>'+t[0]+'</b><br><span style="font-size:32px">'+t[1]+'</span><br><span style="font-size:36px">'+t[2]+'</span><br><small>'+t[3]+'</small></div>'});h+='</div><div style="margin-top:16px;background:#f8faf3;border-radius:14px;padding:16px;line-height:1.8"><b>声调 / Tone:</b> 声调改变音节的高低和意义。Listen for the pitch movement, not only the letters.</div>'}
    if(step===4){var blends=[['h + ao + 3','hǎo','好'],['n + ǐ','nǐ','你'],['lǎo + shī','lǎoshī','老师'],['xiè + xie','xièxie','谢谢'],['zài + jiàn','zàijiàn','再见']];h+='<div style="display:grid;gap:12px">';blends.forEach(function(b){h+='<div style="background:#fff;border:1px solid var(--line);border-radius:16px;padding:18px;text-align:center;font-size:22px"><span>'+b[0]+'</span> <b>→ '+b[1]+'</b> <span style="font-size:34px;margin-left:12px">'+b[2]+'</span></div>'});h+='</div>'}
    if(step===5){var titles=['第一组：单音节','第二组：多音节','第三组：短句'];h+='<div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-bottom:14px">';titles.forEach(function(t,i){h+='<button class="grammar-tab'+(sub===i?' active':'')+'" onclick="ap.pyzSub='+i+';ap.pyzQ=0;ap.pyzAnswer=-1;ap._r()">'+t+'</button>'});h+='</div>';var prompt,answer,opts,total;if(sub===0){prompt=group1[qi%group1.length];answer=toneAnswer[prompt];opts=rotate(toneOptions[prompt],qi);total=15}if(sub===1){var item=group2[qi%group2.length];prompt=item[0];answer=item[1];opts=rotate([answer].concat(group2.filter(function(x){return x[1]!==answer}).slice(0,4).map(function(x){return x[1]})),qi);total=18}if(sub===2){var sent=group3[qi%group3.length];prompt=sent[0];answer=sent[1];opts=rotate([answer,'Nǐ hǎo.','Wǒ hěn hǎo.','Lǎoshī, zàijiàn!'],qi);total=10}var ok=picked>=0&&opts[picked]===answer;h+='<div style="background:#fff;border:1px solid var(--line);border-radius:18px;padding:24px;text-align:center"><div>第 '+(qi+1)+' / '+total+' 题</div><div style="font-size:34px;font-weight:900;margin:14px">'+prompt+'</div><button class="next-btn" onclick="ap._tts('+JSON.stringify(prompt)+')">🔊 听读音</button><div style="display:flex;gap:12px;justify-content:center;flex-wrap:wrap;margin:24px 0">';opts.forEach(function(x,i){h+='<button onclick="ap.pyzAnswer='+i+';ap._r()" style="min-width:130px;padding:14px;border:2px solid '+(picked===i?(ok?'var(--green)':'var(--red)'):'#dbe3ef')+';border-radius:14px;background:'+(picked===i?(ok?'#e8f6ee':'#fff1f2'):'#fff')+';font-size:22px">'+x+'</button>'});h+='</div>'+(picked>=0?'<div style="padding:12px;background:'+(ok?'#e8f6ee':'#fff1f2')+'">'+(ok?'✅ 正确':'❌ 正确答案：'+answer)+'</div>':'')+'<div style="display:flex;justify-content:space-between;margin-top:20px"><button onclick="ap.pyzQ=Math.max(0,ap.pyzQ-1);ap.pyzAnswer=-1;ap._r()">上一题</button><button onclick="ap.pyzQ=(ap.pyzQ+1)%'+total+';ap.pyzAnswer=-1;ap._r()">下一题</button></div></div>'}
    return h+'</div>'; }
  window.L01PinyinLab={render:render};
})();
