import glob
import json
import re
from pathlib import Path

from pypinyin import Style, lazy_pinyin


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "source" / "shared" / "classpro-pinyin-data.js"
HANZI = re.compile(r"[\u3400-\u9fff]")
VISIBLE_KEYS = {
    "acceptable_answers", "answer", "answerKey", "chunks", "clue", "clues",
    "context", "correct_answer", "description", "example", "examples", "frame", "hint",
    "hanzi", "keyword", "keywords", "left", "options", "passage", "passageParts",
    "phrases", "prompt_cn", "question", "question_cn", "right", "sentence", "sentences",
    "scene", "scene_cn", "source", "source_sentence", "starter", "statement", "steps",
    "stimulus", "target", "task", "template", "title", "word", "wordBank", "words",
    "instructions", "output",
}


def collect(value, parent_key="", found=None):
    found = found if found is not None else set()
    if isinstance(value, str):
        if parent_key in VISIBLE_KEYS and HANZI.search(value):
            found.add(value)
    elif isinstance(value, list):
        for item in value:
            collect(item, parent_key, found)
    elif isinstance(value, dict):
        for key, item in value.items():
            collect(item, key, found)
    return found


def annotated_pinyin(text):
    readings = lazy_pinyin(
        text,
        style=Style.TONE,
        neutral_tone_with_five=False,
        errors="ignore",
    )
    hanzi = HANZI.findall(text)
    for index, char in enumerate(hanzi):
        if char != "得":
            continue
        previous = hanzi[index - 1] if index else ""
        following = hanzi[index + 1] if index + 1 < len(hanzi) else ""
        if previous == "觉" or following == "到" or (previous == "不" and following == "不"):
            continue
        readings[index] = "de"
    return " ".join(syllable.lower() for syllable in readings if syllable).strip()


def main():
    strings = set()
    pattern = str(ROOT / "source" / "data-model" / "lessons" / "HSK3-L*.json")
    for filename in sorted(glob.glob(pattern)):
        with open(filename, encoding="utf-8") as source:
            collect(json.load(source), found=strings)
    fragments = set()
    for text in strings:
        for fragment in re.findall(r"[\u3400-\u9fff]+", text):
            fragments.add(fragment)
            fragments.update(fragment)
    strings.update(fragments)
    lookup = {text: annotated_pinyin(text) for text in sorted(strings)}
    payload = json.dumps(lookup, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "// Generated by scripts/build-classpro-pinyin-data.py. Do not edit by hand.\n"
        "window.ClassProPinyinData=" + payload + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({len(lookup)} entries)")


if __name__ == "__main__":
    main()
